"""add_summary_to_sources

Revision ID: 22cc258423df
Revises: 0002
Create Date: 2026-04-11 03:51:01.710998

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '22cc258423df'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_messages', 'role',
               existing_type=postgresql.ENUM('user', 'assistant', name='message_role'),
               type_=sa.Enum('user', 'assistant', name='message_role', native_enum=False),
               existing_nullable=False)
    op.drop_index('idx_chat_messages_notebook_id_created', table_name='chat_messages')
    op.alter_column('export_jobs', 'format',
               existing_type=postgresql.ENUM('pdf', 'mind_map', 'docx', 'pptx', 'xlsx', name='export_format'),
               type_=sa.Enum('PDF', 'MIND_MAP', 'DOCX', 'PPTX', 'XLSX', name='exportformat'),
               existing_nullable=False)
    op.alter_column('export_jobs', 'status',
               existing_type=postgresql.ENUM('queued', 'processing', 'done', 'failed', name='job_status'),
               type_=sa.Enum('QUEUED', 'PROCESSING', 'DONE', 'FAILED', name='jobstatus'),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::job_status"))
    op.drop_index('idx_notebooks_user_id', table_name='notebooks')
    op.add_column('sources', sa.Column('summary', sa.Text(), nullable=True))
    op.drop_index('idx_sources_notebook_id', table_name='sources')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sources_notebook_id', 'sources', ['notebook_id'], unique=False)
    op.drop_column('sources', 'summary')
    op.create_index('idx_notebooks_user_id', 'notebooks', ['user_id'], unique=False)
    op.alter_column('export_jobs', 'status',
               existing_type=sa.Enum('QUEUED', 'PROCESSING', 'DONE', 'FAILED', name='jobstatus'),
               type_=postgresql.ENUM('queued', 'processing', 'done', 'failed', name='job_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'queued'::job_status"))
    op.alter_column('export_jobs', 'format',
               existing_type=sa.Enum('PDF', 'MIND_MAP', 'DOCX', 'PPTX', 'XLSX', name='exportformat'),
               type_=postgresql.ENUM('pdf', 'mind_map', 'docx', 'pptx', 'xlsx', name='export_format'),
               existing_nullable=False)
    op.create_index('idx_chat_messages_notebook_id_created', 'chat_messages', ['notebook_id', 'created_at'], unique=False)
    op.alter_column('chat_messages', 'role',
               existing_type=sa.Enum('user', 'assistant', name='message_role', native_enum=False),
               type_=postgresql.ENUM('user', 'assistant', name='message_role'),
               existing_nullable=False)
    # ### end Alembic commands ###
